Push-Location $PSScriptRoot

$commitDescription = "" + (.\show-current-commit.ps1)

$self = $MyInvocation.MyCommand.Path
"// Generated by: [$self]"
"// Commit:       [$commitDescription]"
""
"namespace SoundMetrics {"
"    public static class CommitDescription {"
"        public static readonly string Value = ""$commitDescription"";"
"    }"
"}"

Pop-Location
